export const routes = {
  dashboard: "/dashboard",
  schedule: "/schedule",
  routeAssignments: "/route-assignments",
  contacts: "/contacts",
  contactDetail: (id: string) => `/contacts/${id}`,
  clientMap: "/client-map",
  projects: "/projects",
  maintenanceItems: "/maintenance-items",
  maintenancePlans: "/maintenance-plans",
  bidItems: "/bid-items",
  bids: "/bids",
  bidsCreate: "/bids/create",
  bidsEstimate: "/bids/estimate",
  doorToDoor: "/door-to-door",
  hardCosts: "/hard-costs",
  payments: "/payments",
  communications: "/communications",
  financials: "/financials",
  settings: "/settings",
  importContacts: "/import-contacts",
  paymentSuccess: "/payment-success",
  paymentCancel: "/payment-cancel",
} as const;
