/**
 * SupabaseEntityStore — drop-in replacement for MockEntityStore.
 * Mirrors the same interface (list/filter/get/create/update/delete/bulkCreate)
 * so swapping the `db` export in src/data/api.ts requires no other code changes.
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import type { BaseEntity } from "@/data/types";
import { getSupabaseAdmin } from "./admin";
import { createSupabaseBrowserClient } from "./client";

// Fields that the UI sometimes passes in filter criteria but don't exist as
// columns. We're single-tenant, so company_id is meaningless — silently drop it.
const IGNORED_FILTER_KEYS = new Set(["company_id"]);

// Fields we never write back during create/update — generated by Postgres.
const STRIPPED_WRITE_KEYS = new Set(["id", "created_date", "updated_date", "company_id"]);

function getClient(): SupabaseClient {
  // On the server, use the admin (service role) client so we bypass RLS until
  // auth is wired. In the browser we use the public anon client.
  if (typeof window === "undefined") return getSupabaseAdmin();
  return createSupabaseBrowserClient();
}

function stripWriteKeys<T extends Record<string, unknown>>(obj: T): Partial<T> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (STRIPPED_WRITE_KEYS.has(k)) continue;
    if (v === undefined) continue;
    out[k] = v;
  }
  return out as Partial<T>;
}

export class SupabaseEntityStore<T extends BaseEntity> {
  constructor(private readonly table: string) {}

  async list(): Promise<T[]> {
    const client = getClient();
    const { data, error } = await client.from(this.table).select("*");
    if (error) throw new Error(`[${this.table}] list failed: ${error.message}`);
    return (data ?? []) as T[];
  }

  async filter(criteria: Partial<T>, sort?: string): Promise<T[]> {
    const client = getClient();
    let query = client.from(this.table).select("*");

    for (const [key, value] of Object.entries(criteria)) {
      if (value === undefined || value === null) continue;
      if (IGNORED_FILTER_KEYS.has(key)) continue;
      query = query.eq(key, value as never);
    }

    if (sort) {
      const desc = sort.startsWith("-");
      const field = desc ? sort.slice(1) : sort;
      query = query.order(field, { ascending: !desc });
    }

    const { data, error } = await query;
    if (error) throw new Error(`[${this.table}] filter failed: ${error.message}`);
    return (data ?? []) as T[];
  }

  async get(id: string): Promise<T | null> {
    const client = getClient();
    const { data, error } = await client.from(this.table).select("*").eq("id", id).maybeSingle();
    if (error) throw new Error(`[${this.table}] get failed: ${error.message}`);
    return (data ?? null) as T | null;
  }

  async create(data: Partial<Omit<T, "id" | "created_date" | "updated_date">>): Promise<T> {
    const client = getClient();
    const payload = stripWriteKeys(data as Record<string, unknown>);
    const { data: row, error } = await client
      .from(this.table)
      .insert(payload as never)
      .select()
      .single();
    if (error) throw new Error(`[${this.table}] create failed: ${error.message}`);
    return row as T;
  }

  async update(id: string, data: Partial<T>): Promise<T | null> {
    const client = getClient();
    const payload = stripWriteKeys(data as Record<string, unknown>);
    const { data: row, error } = await client
      .from(this.table)
      .update(payload as never)
      .eq("id", id)
      .select()
      .maybeSingle();
    if (error) throw new Error(`[${this.table}] update failed: ${error.message}`);
    return (row ?? null) as T | null;
  }

  async delete(id: string): Promise<boolean> {
    const client = getClient();
    const { error, count } = await client
      .from(this.table)
      .delete({ count: "exact" })
      .eq("id", id);
    if (error) throw new Error(`[${this.table}] delete failed: ${error.message}`);
    return (count ?? 0) > 0;
  }

  async bulkCreate(
    dataArray: Partial<Omit<T, "id" | "created_date" | "updated_date">>[]
  ): Promise<T[]> {
    if (dataArray.length === 0) return [];
    const client = getClient();
    const payload = dataArray.map((d) => stripWriteKeys(d as Record<string, unknown>));
    const { data, error } = await client.from(this.table).insert(payload as never).select();
    if (error) throw new Error(`[${this.table}] bulkCreate failed: ${error.message}`);
    return (data ?? []) as T[];
  }
}
